# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateField(auto_now_add=True)),
                ('station', models.CharField(blank=True, default=' ', max_length=100)),
                ('tpm', models.CharField(blank=True, default=' ', max_length=100)),
                ('temp', models.CharField(blank=True, default=' ', max_length=100)),
            ],
        ),
    ]
